rjob submit \
--name=debug-flowrl-qwen25-05b-dapo-math \
--gpu=4 \
--memory=400000 \
--cpu=64 \
--charged-group=llmit_gpu \
--private-machine=group \
--mount=gpfs://gpfs1/llmit:/mnt/shared-storage-user/llmit \
--mount=gpfs://gpfs1/large-model-center-share-weights:/mnt/shared-storage-user/large-model-center-share-weights \
--mount=gpfs://gpfs1/llmrazor-share:/mnt/shared-storage-user/llmrazor-share \
--image=registry.h.pjlab.org.cn/ailab-puyu/xpuyu:torch-2.7.0-076676dd-0708 \
-P 1 \
--gang-start=true \
--host-network=true \
-e DISTRIBUTED_JOB=true \
--custom-resources rdma/mlnx_shared=4 \
--custom-resources mellanox.com/mlnx_rdma=1 \
-- bash /mnt/shared-storage-user/llmit/user/xuekaizhu/verl_FlowRL/recipe/flowrl/intern-s2/run_flowrl_debug.sh